### ISSUE TITLE
Userscript Metadata

### ISSUE THREAD

**Issue by Martii** [rslifka/fate_of_all_fools#1]
Hi there,

Welcome to OUJS from the current Admin.

I have a suggestion for your Userscript. You figured out the `@supportURL` instead of [your comment here](https://openuserjs.org/scripts/rslifka/FateOfAllFools_-_DIM_Customization/issues/Please_submit_isses_over_at_GitHub,_thanks!)... nicely done. You may want to do this as well perhaps in between [/rslifka/fate_of_all_fools/blob/`8bd4fee`/fateOfAllFools.user.js#L17-L18](https://github.com/rslifka/fate_of_all_fools/blob/8bd4feeb7d82d9da68620eeb0f0f464095bcbe7f/fateOfAllFools.user.js#L17-L18):

``` js
// @license MIT; https://raw.githubusercontent.com/rslifka/fate_of_all_fools/master/LICENSE.txt
// @copyright 2017, Robert Slifka (https://github.com/rslifka)
```

We will show the license and copyright. *(Example at [oujs - Meta View](https://openuserjs.org/scripts/Marti/oujs_-_Meta_View))*.

Thanks for the consideration and merry scripting. :)

Refs:
* [@license](https://sourceforge.net/p/greasemonkey/wiki/Metadata_Block/#license). Since you have a LICENSE file you can point it to the raw source. If you don't, perhaps in the future for some reason, you can always point it to the generic form at https://opensource.org/licenses/MIT
* [@copyright](https://sourceforge.net/p/greasemonkey/wiki/Metadata_Block/#copyright). Alternatively the Author Website could be your user page at OUJS if you wish.

**Comment by Martii** [comment]
One more quick thing if I may. [The OUJS FAQ](https://openuserjs.org/about/Frequently-Asked-Questions) may interest you particularly [Q: Does OpenUserJS.org have meta?](https://openuserjs.org/about/Frequently-Asked-Questions#q-does-openuserjs-org-have-meta-).

Thanks for the moment.

**Comment by rslifka** [comment]
Thank you @Martii! I will have a look 👍
