### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by Reynbow** [rslifka/fate_of_all_fools#127]
I cannot see that it does anything to DIM at all.

**Comment by rslifka** [comment]
Yep, I haven't been making changes, but I continue to use it every day.

**Comment by Reynbow** [comment]
> Yep, I haven't been making changes, but I continue to use it every day and it works. What are you having an issue with?

well, it's not so much that I have an issue it's just that the **only** thing I can see it doing is changing the background to black
that's it
so I'm guessing there must be something wrong, since that's a lot of effort to make the background go from dark grey to black

**Comment by rslifka** [comment]
Got it, thanks! I'll do a fresh install on a second machine to see if I run into any issues like that.

**Comment by rslifka** [comment]
![CleanShot 2024-05-30 at 12 32 37@2x](https://github.com/rslifka/fate_of_all_fools/assets/231435/0ec97b1d-9ee6-4df9-8a9f-00763f5521a2)

It works! It's likely that it's just unclear what next steps are :)
