### ISSUE TITLE
Something broke ?

### ISSUE THREAD

**Issue by per1970** [rslifka/fate_of_all_fools#49]
Hi, I was trying to install this seemingly excellent tweak to DIM, but things does not seem to work.
 the error I'm seeing is:
Tampermonkey: couldn't load @require from URL https://github.com/rslifka/fate_of_all_fools/releases/download/current/fateOfAllFools.js==

I double checked (removing the == at the end gives the same error) and it seems there is no release version available?!

intentional or snafu ?

**Comment by rslifka** [comment]
Hi @per1970! Hmm that's odd... no change to the UserScript or the build scripts for some time. Release looks good at the moment (in spite of the strange TravisCI infinite loop :)

Is it still happening? Apologies for the late reply - still not getting GitHub issue notifications.

**Comment by per1970** [comment]
Argh yes...Travis is...at times a pain..I wish I could go pro version.

But yes, still problems. The @require links points to non existent files.

infact the whole https://github.com/rslifka/fate_of_all_fools/releases is empty. and I guess tampermonkey goes a little wonky (woha...I'm a poet and I didn't know it!!!)

btw: i used the install script on OpenUserJS

**Comment by rslifka** [comment]
Confirmed! I am in the process of redoing this after a great suggestion from a friend. Will hopefully be up this evening. Thanks for your patience!

**Comment by rslifka** [comment]
OK sir, should be working now! You'll need to update to the latest version and you'll be all set.
