### ISSUE TITLE
Relocate "FATE Config" as it overlays / is hidden by character and vault contents

### ISSUE THREAD

**Issue by IrealiTY** [rslifka/fate_of_all_fools#53]
Hey hey,
when I load in the script DIM becomes dark as it should, I see the "faves" and tooltips loaded from your own .tsv but no matter what I do, the FATE Config button is missing.

I saw it once a few weeks ago but since then it disappeared.
Chrome error log doesn't say anything in particular and I tried to disable/enable random DIM options thinking it might be related.

**Comment by rslifka** [comment]
I made some pretty big changes yesterday to how the script is installed and updated. Can you re-install and let me know?

You'll know if you're on the older version by checking the `Externals` tab in TamperMonkey, if it says `URL https://github.com/rslifka/fate_of_all_fools/releases/download/current/fateOfAllFools.js` then you need to update :)

**Comment by rslifka** [comment]
Reproduced and verified fixed. Let me know if it comes up again!

**Comment by IrealiTY** [comment]
Can't confirm it :(
I updated to 2520 and it's still missing.

Attached a screenshot of how it looks to me :)
![image](https://user-images.githubusercontent.com/1223686/41620677-c58501c8-740a-11e8-9221-fdbc57e53e84.png)

**Comment by IrealiTY** [comment]
Ok sorry, it does work I had to clear cache twice for some reason

**Comment by IrealiTY** [comment]
Huh.. it seems super inconsistent... one reload its gone another one its back, maybe add the button to the navigation? Next to What's New or so?

**Comment by rslifka** [comment]
Oh wow, that's a lot of gear. I only have one character so there's never anything on that part of my screen :)  Will relocate!

**Comment by IrealiTY** [comment]
Hahaha not enough Vault Space! But yeah, thanks for looking into it.
I forked it myself and tried to change the jQuery append from body to the menu list but it was the same issue, never loading the config

**Comment by rslifka** [comment]
You're all set! Let me know if there are any issues :)
