### ISSUE TITLE
Slowdown over time.

### ISSUE THREAD

**Issue by per1970** [rslifka/fate_of_all_fools#61]
I've noticed that the response (clicking on an item, mous over on upgrades..etc.) becomes VERY slow (15-30 seconds delayed) after FOAF has been active for a longer time (6-9 hours)

After digging it seems the GPU process for the web page is VERY busy. I see a large memory usage (1GB+) and a wild fluctuation in actual CPU load (10%-100%) 

 Unfortunately I'm unable to run the Performance tool on an already running page :( so I don't have any proper metrics to provide you with.

But reloading the page clean things up.

What it feels like to me is some sort of redraw/cleanup routine is being naughty :)

Oh and I'm one of those "No-lifers" with 3 characters and a 99% full vault, so LOTS of items :)

**Comment by rslifka** [comment]
Going to close this one. I'm always working on it - will never be "done" :)
