### ISSUE TITLE
No faves/notes while in infusion finder

### ISSUE THREAD

**Issue by per1970** [rslifka/fate_of_all_fools#62]
![capture](https://user-images.githubusercontent.com/4106324/42124902-1f18d6b0-7c6c-11e8-8746-e211cb0df704.png)

As you can see from the picture, no fav markings or link to the spreadsheet.

**Comment by rslifka** [comment]
Hi @per1970 and thanks for the heads up! I've fixed styling so things look FOAF-like in this dialog however it's a considerable amount of work to make this dialog function like the general view. As a plugin on top of a web-app, some things that seem like they should be easy aren't so much :)
